spring:
  application:
    name: parking-management-api
  datasource:
    url: jdbc:h2:mem:parking
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console